blank_issues_enabled: false
contact_links:
  - name: Support question 🙋
    url: https://github.com/dnadesign/silverstripe-browser-update/discussions/new
    about: Please ask and answer questions here.
