name: Test 🧑‍🔬

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: dev-main

jobs:
  test:
    # Pinning Ubuntu 24.04 removes the migration notice and prevents an unexpected switch to Ubuntu 26
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SS_mysite
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      # Updating to checkout@v6 removes warning: Node.js 20 is deprecated
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      # Updating to composer-install@v4 removes warning: Node.js 20 is deprecated
      - uses: ramsey/composer-install@v4

      - run: vendor/bin/sake db:build --flush
        env:
          SS_DATABASE_SERVER: 127.0.0.1
          SS_DATABASE_NAME: SS_mysite
          SS_DATABASE_USERNAME: root
          SS_DATABASE_PASSWORD: root

      - run: vendor/bin/phpunit -d flush=1
        env:
          SS_DATABASE_SERVER: 127.0.0.1
          SS_DATABASE_NAME: SS_mysite
          SS_DATABASE_USERNAME: root
          SS_DATABASE_PASSWORD: root
